### ISSUE TITLE
Agent fails with error for some runs

### ISSUE THREAD

**Issue by CosminGramada** [reportportal/agent-js-playwright#35]
There are some runs for which the agent fails with the below exception leaving the launch and some tests inside it as InProgress.

```/src/node_modules/@reportportal/agent-js-playwright/build/reporter.js:286
        var projectName = !orderedSuites[lastSuiteIndex].location // Update this after https://github.com/microsoft/playwright/issues/10306
                                                         ^
TypeError: Cannot read property 'location' of undefined
    at RPReporter.createSuites (/src/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:265:56)
    at RPReporter.onTestBegin (/src/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:309:30)
    at Multiplexer.onTestBegin (/src/node_modules/@playwright/test/lib/reporters/multiplexer.js:45:132)
    at Worker.onTestBegin (/src/node_modules/@playwright/test/lib/dispatcher.js:186:190)
    at Worker.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/src/node_modules/@playwright/test/lib/dispatcher.js:585:12)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)```
    
```
"@playwright/test": "^1.18.1"
"@reportportal/agent-js-playwright": "^5.0.2"
ReportPortal version: API Service: 5.6.3;Jobs Service: 5.6.3;Authorization Service: 5.6.3;Service UI: 5.6.0;
```

**Comment by AmsterGet** [comment]
Hello @CosminGramada !
Could you please share your tests structure examples? I mean do you use nested playwright describe or test calls and do you use splitting runs by projects?
As mentioned in the error line comment, this was a temporary and not stable solution until the playwright team adds support for the project name property to the suite. Seems like now it is available (according to [Playwright 1.19](https://playwright.dev/docs/api/class-suite#suite-project)) and we need to do small refactoring on it.

**Comment by CosminGramada** [comment]
Hello @AmsterGet, thank you for your fast reply.
Yes, it seemed the nested `describe` was the culprit, everything works fine after i removed it.

**Comment by oranje322** [comment]
Hello @CosminGramada ,
Could you please share your tests structure examples and playwright config structure?

**Comment by CosminGramada** [comment]
@AmsterGet @oranje322 
Sorry for the delay, it seems that this one slipped under my radar.


Below you can find the details:
```
import { PlaywrightTestConfig } from '@playwright/test';

const RPconfig = {
    'token': '<token>',
    'endpoint': '<endpoint>',
    'project': 'frontend',
    'launch': `${process.env.CI_PIPELINE_ID}-${process.env.CI_JOB_NAME}`,
    'attributes': [
        {
            key: 'Project',
            value: process.env.CI_PROJECT_TITLE ?? 'N/A'
        },
        {
            key: 'Branch',
            value: process.env.CI_COMMIT_REF_NAME ?? 'N/A'
        },
    ],
    'restClientConfig': {
        timeout: 240000
    },
    'skippedIssue': false
};

const config: PlaywrightTestConfig = {
    use: {
        headless: true,
        ignoreHTTPSErrors: true,
        actionTimeout: 10000,
        navigationTimeout: 10000,
        screenshot: 'only-on-failure',
    },
    expect: {
        timeout: 10000
    },
    testMatch: '**.e2e-spec.ts',
    timeout: 120000,
    reporter: [
        ['list'],
        ['@reportportal/agent-js-playwright', RPconfig]
    ],
    retries: 2,
    projects: [
        {
            name: 'Project1',
            testMatch: '**/Project1/**/*.e2e-spec.ts',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    devtools: false,
                    args: ['--disable-dev-shm-usage']
                },
                viewport: { height: 900, width: 1440 },
            },
        },
        {
            name: 'Project2',
            testMatch: '**/Project2/**/*.e2e-spec.ts',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    devtools: false,
                    args: ['--disable-dev-shm-usage']
                },
                viewport: { height: 900, width: 1440 },
            },
        },
        {
            name: 'Project3',
            testMatch: '**/Project3/**/*.e2e-spec.ts',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    devtools: false,
                    args: ['--disable-dev-shm-usage']
                },
                viewport: { height: 900, width: 1440 },
            },
        },
        {
            name: 'Project4',
            testMatch: '**/Project4/**/*.e2e-spec.ts',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    devtools: false,
                    args: ['--disable-dev-shm-usage']
                },
                viewport: { height: 900, width: 1440 },
            },
        },
        {
            name: 'Project5',
            testMatch: '**/Project5/**/*.e2e-spec.ts',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    devtools: false,
                    args: ['--disable-dev-shm-usage']
                },
                viewport: { height: 900, width: 1440 },
            },
        }
    ],
};
export default config;
```

```
root
---src
------tests
---------Project1
------------test_files_name-1.e2e-spec.ts
------------test_files_name-2.e2e-spec.ts
..
------------test_files_name-n.e2e-spec.ts
---------Project2
------------test_files_name-1.e2e-spec.ts
------------test_files_name-2.e2e-spec.ts
..
------------test_files_name-n.e2e-spec.ts
---------Project3
------------test_files_name-1.e2e-spec.ts
------------test_files_name-2.e2e-spec.ts
..
------------test_files_name-n.e2e-spec.ts
---------Project4
------------test_files_name-1.e2e-spec.ts
------------test_files_name-2.e2e-spec.ts
..
------------test_files_name-n.e2e-spec.ts
---------Project5
------------subfolder1
---------------test_files_name-1.e2e-spec.ts
---------------test_files_name-2.e2e-spec.ts
..
---------------test_files_name-n.e2e-spec.ts
------------subfolder2
---------------test_files_name-1.e2e-spec.ts
---------------test_files_name-2.e2e-spec.ts
..
---------------test_files_name-n.e2e-spec.ts
------------subfolder3
---------------test_files_name-1.e2e-spec.ts
---------------test_files_name-2.e2e-spec.ts
..
---------------test_files_name-n.e2e-spec.ts
------other folders
```

Let me know if this answer your questions.

**Comment by oranje322** [comment]
@CosminGramada
Could you also share the structure of the test example inside the file?
Preferably with an example before you remove the nested `describe`.
> Hello @AmsterGet, thank you for your fast reply. Yes, it seemed the nested `describe` was the culprit, everything works fine after i removed it.

**Comment by CosminGramada** [comment]
@oranje322 Here it is:


```
//<imports section>

test.describe('Suite name', () => {
    //<suite variables declaration / initialization>
    test.beforeAll(async () => {
        //beforeAll logic here
    });

    for(const item of itemList) {
        test.describe('Sub-suite name 1', () => {
            test.beforeEach(async ({ page }) => {
                //beforeEach logic here
            });

            test('Test name 1', async() => {
                //test here
            });

            test('Test name 2', async() => {
                //test here
            });
        });

        test.describe('Sub-suite name 2', () => {
            test.beforeEach(async ({ page }) => {
                //beforeEach logic here
            });

            test('Test name 3', async() => {
                //test here
            });

            test('Test name 4', async() => {
                //test here
            });
        });
    }
});
```

**Comment by oranje322** [comment]
Hello, @CosminGramada ,
Could you check this bug in the new 5.0.3 version of the agent?

**Comment by AmsterGet** [comment]
Hello @CosminGramada !
I'll close the issue, feel free to reopen if issue still exists.
