### ISSUE TITLE
Unable to run example tests with reporter - Cannot read properties of undefined (reading 'rootSuite')

### ISSUE THREAD

**Issue by shwarcu** [reportportal/agent-js-playwright#56]
Hi, 
I created repository for problem reproduction https://github.com/shwarcu/playwright-reportportal-example.
Here is how I got up to this point:
I deployed ReportPortal locally with docker and created initial tests setup with `npm init playwright@latest`.
Then I added `agent-js-playwright` reporter to the config and changed `testDir` to take tests from `./tests-examples`.

When running example tests I keep getting this error:

```shell
Running 50 tests using 4 workers

  ✓  1 [chromium] › demo-todo-app.spec.ts:61:3 › New Todo › should show #main and #footer when items added (1s)
  ✓  2 [chromium] › demo-todo-app.spec.ts:14:3 › New Todo › should allow me to add todo items (1s)
  ✓  3 [chromium] › demo-todo-app.spec.ts:47:3 › New Todo › should append new items to the bottom of the list (1s)
  ✓  4 [chromium] › demo-todo-app.spec.ts:37:3 › New Todo › should clear text input field when an item is added (1s)
  ✓  5 [chromium] › demo-todo-app.spec.ts:81:3 › Mark all as completed › should allow me to mark all items as completed (795ms)
     6 [chromium] › demo-todo-app.spec.ts:90:3 › Mark all as completed › should allow me to clear the complete state of all items
     7 [chromium] › demo-todo-app.spec.ts:99:3 › Mark all as completed › complete all checkbox should update state when items are completed / cleared
     8 [chromium] › demo-todo-app.spec.ts:122:3 › Item › should allow me to mark items as complete
/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:462
                        rootSuiteName = parentObj.rootSuite;
                                                  ^

TypeError: Cannot read properties of undefined (reading 'rootSuite')
    at RPReporter.<anonymous> (/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:483:37)
    at step (/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:60:23)
    at Object.next (/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:41:53)
    at /home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:35:71
    at new Promise (<anonymous>)
    at __awaiter (/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:31:12)
    at RPReporter.onTestEnd (/home/maciej/workspace/playwright-reportportal-example/node_modules/@reportportal/agent-js-playwright/build/reporter.js:423:16)
    at /home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/reporters/multiplexer.js:69:131
    at wrap (/home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/reporters/multiplexer.js:119:5)
    at Multiplexer.onTestEnd (/home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/reporters/multiplexer.js:66:45)
    at Dispatcher._reportTestEnd (/home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/dispatcher.js:574:159)
    at Worker.onTestEnd (/home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/dispatcher.js:240:12)
    at Worker.emit (node:events:390:28)
    at ChildProcess.<anonymous> (/home/maciej/workspace/playwright-reportportal-example/node_modules/@playwright/test/lib/dispatcher.js:633:12)
    at ChildProcess.emit (node:events:390:28)
```

Related issue https://github.com/reportportal/agent-js-playwright/issues/42
Probably regression from last release?

**Comment by rafalszmit** [comment]
I also see these errors lately:
```
(node:9318) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rootSuite' of undefined
583    at RPReporter.<anonymous> ([<path hid by me>]/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:483:37)
584    at step ([<path hid by me>]/node_modules/@reportportal/agent-js-playwright/build/reporter.js:60:23)
585    at Object.next ([<path hid by me>]/node_modules/@reportportal/agent-js-playwright/build/reporter.js:41:53)
586    at fulfilled ([<path hid by me>]/node_modules/@reportportal/agent-js-playwright/build/reporter.js:32:58)
587(Use `node --trace-warnings ...` to show where the warning was created)
588(node:9318) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
589(node:9318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The reportportal shows that the jobs are running even tho they were finished on CI. Nothing was changed by us around configuration and it was working in past with no issues.

it is present on versions (the only ones I checked so far):
"@reportportal/agent-js-playwright": "^5.0.2",
"@reportportal/agent-js-playwright": "^5.0.5",

**Comment by MichalFidor** [comment]
Something has happened between 15.08.2022 11:30 CET time - this was the last run we've had in a project and everything was okay. The first occurrence I've spotted at 15.08.2022 21:00 CET time after this date almost every run contains this error.

**Comment by AmsterGet** [comment]
Hello guys!
We have released a version 5.0.6 with a fix.
Could you confirm that this fixes the issue?

**Comment by shwarcu** [comment]
@AmsterGet Hi, I will check that afternoon when I'm done with my daily duties ;)

**Comment by shwarcu** [comment]
Hi, sorry for delayed response. After updating the package, it is indeed working without errors 💯
